#!/usr/bin/env python3
"""Generate coverage maps and strike plans from atom-registry.yaml.

Outputs:
  docs/archive/coverage/by-node.md
  docs/archive/coverage/by-pillar.md
  docs/archive/coverage/by-provenance.md
  docs/archive/coverage/by-nature.md
  docs/archive/strikes/phase-1.md
  docs/archive/strikes/phase-2.md
  docs/archive/strikes/phase-3.md
  docs/archive/strikes/phase-4.md
  docs/archive/strikes/phase-5.md
"""

import os
import sys
from collections import defaultdict
from datetime import datetime, timezone

import yaml

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY_PATH = os.path.join(PROJECT_ROOT, "docs", "archive", "atom-registry.yaml")
COVERAGE_DIR = os.path.join(PROJECT_ROOT, "docs", "archive", "coverage")
STRIKES_DIR = os.path.join(PROJECT_ROOT, "docs", "archive", "strikes")

NODE_NAMES = {
    1: "Feel Good First",
    2: "Your Body Is the Starting Point",
    3: "Stabilize Your Blood Sugar",
    4: "Your Nervous System Is the Filter",
    5: "Sleep Is Non-Negotiable",
    6: "Awareness Creates Choice",
    7: "You're Not Your Thoughts",
    8: "Patterns Run Until Seen",
    9: "Your Reality Is Interpreted",
    10: "Radical Responsibility (with Love)",
    11: "You Can't Change What You Won't Acknowledge",
    12: "Integrity Builds Self-Trust",
    13: "Systems Create Freedom",
}

PILLAR_ORDER = ["Physical", "Inner", "Identity", "Financial", "Cross-cutting"]
PROVENANCE_ORDER = ["LOCAL", "HYBRID", "ALIEN"]

# Build priority: MISSING > PARTIAL > EXISTS > N/A
BUILD_PRIORITY = {"MISSING": 0, "PARTIAL": 1, "EXISTS": 2, "N/A": 3}


def load_registry():
    """Parse the atom registry line-by-line to handle malformed YAML values.

    The registry is generated by awk and may contain unescaped quotes or
    special characters that break strict YAML parsing. This parser reads
    the known fixed-schema format directly.
    """
    atoms = []
    current = None

    with open(REGISTRY_PATH, "r") as f:
        for line in f:
            stripped = line.rstrip("\n")

            # New atom entry
            if stripped.startswith("  - id: "):
                if current is not None:
                    atoms.append(current)
                current = {"id": stripped[len("  - id: "):].strip()}
                continue

            if current is None:
                continue

            # Key-value fields (4-space indent)
            if stripped.startswith("    ") and ": " in stripped:
                key_val = stripped[4:]
                colon_pos = key_val.index(": ")
                key = key_val[:colon_pos]
                val = key_val[colon_pos + 2:]

                # Strip surrounding quotes
                if val.startswith('"') and val.endswith('"'):
                    val = val[1:-1]
                elif val.startswith('"'):
                    # Malformed quote — just strip leading quote
                    val = val[1:]

                # Parse typed values
                if key == "nodes":
                    # Parse [1, 2, 3] or []
                    val = val.strip()
                    if val == "[]":
                        val = []
                    elif val.startswith("[") and val.endswith("]"):
                        inner = val[1:-1]
                        val = [int(x.strip()) for x in inner.split(",") if x.strip()]
                    else:
                        val = []
                elif key in ("position", "of_total"):
                    try:
                        val = int(val)
                    except (ValueError, TypeError):
                        val = 0

                current[key] = val

    # Don't forget the last atom
    if current is not None:
        atoms.append(current)

    return atoms


def timestamp():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def esc(text):
    """Escape pipe characters for markdown tables."""
    if not text:
        return ""
    return str(text).replace("|", "\\|")


def truncate(text, maxlen=80):
    """Truncate idea text for table display."""
    text = esc(text)
    if len(text) > maxlen:
        return text[: maxlen - 3] + "..."
    return text


# ---------------------------------------------------------------------------
# Coverage Map: By Node
# ---------------------------------------------------------------------------
def generate_by_node(atoms):
    node_atoms = defaultdict(list)
    for atom in atoms:
        nodes = atom.get("nodes", [])
        if isinstance(nodes, list):
            for n in nodes:
                node_atoms[n].append(atom)
        elif isinstance(nodes, int):
            node_atoms[nodes].append(atom)

    lines = [
        "# Coverage Map: By Node",
        "",
        f"Generated: {timestamp()}",
        f"Total atoms in registry: {len(atoms)}",
        "",
        "---",
        "",
    ]

    for node_id in sorted(NODE_NAMES.keys()):
        node_name = NODE_NAMES[node_id]
        group = node_atoms.get(node_id, [])
        total = len(group)
        exists = sum(1 for a in group if a.get("build_state") == "EXISTS")
        partial = sum(1 for a in group if a.get("build_state") == "PARTIAL")
        missing = sum(1 for a in group if a.get("build_state") == "MISSING")
        na = sum(1 for a in group if a.get("build_state") == "N/A")

        lines.append(f"## Node {node_id} — {node_name}")
        lines.append(
            f"Total atoms: {total} | EXISTS: {exists} | PARTIAL: {partial} | MISSING: {missing} | N/A: {na}"
        )
        lines.append("")

        if group:
            lines.append(
                "| ID | Source | Idea | Provenance | Nature | Build State |"
            )
            lines.append(
                "|-----|--------|------|------------|--------|-------------|"
            )
            # Sort by build priority (MISSING first), then ID
            sorted_group = sorted(
                group,
                key=lambda a: (
                    BUILD_PRIORITY.get(a.get("build_state", "N/A"), 99),
                    a.get("id", ""),
                ),
            )
            for a in sorted_group:
                lines.append(
                    f"| {a.get('id', '')} "
                    f"| {esc(a.get('source_file', ''))} "
                    f"| {truncate(a.get('idea', ''))} "
                    f"| {a.get('provenance', '')} "
                    f"| {a.get('nature', '')} "
                    f"| {a.get('build_state', '')} |"
                )
        else:
            lines.append("*No atoms mapped to this node.*")

        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Coverage Map: By Pillar
# ---------------------------------------------------------------------------
def generate_by_pillar(atoms):
    pillar_atoms = defaultdict(list)
    for atom in atoms:
        pillar = atom.get("pillar", "Unknown")
        pillar_atoms[pillar].append(atom)

    lines = [
        "# Coverage Map: By Pillar",
        "",
        f"Generated: {timestamp()}",
        f"Total atoms in registry: {len(atoms)}",
        "",
        "## Summary",
        "",
        "| Pillar | Total | EXISTS | PARTIAL | MISSING | N/A |",
        "|--------|-------|--------|---------|---------|-----|",
    ]

    for pillar in PILLAR_ORDER:
        group = pillar_atoms.get(pillar, [])
        total = len(group)
        exists = sum(1 for a in group if a.get("build_state") == "EXISTS")
        partial = sum(1 for a in group if a.get("build_state") == "PARTIAL")
        missing = sum(1 for a in group if a.get("build_state") == "MISSING")
        na = sum(1 for a in group if a.get("build_state") == "N/A")
        lines.append(
            f"| {pillar} | {total} | {exists} | {partial} | {missing} | {na} |"
        )

    # Catch any pillars not in the canonical list
    other_pillars = sorted(set(pillar_atoms.keys()) - set(PILLAR_ORDER))
    for pillar in other_pillars:
        group = pillar_atoms[pillar]
        total = len(group)
        exists = sum(1 for a in group if a.get("build_state") == "EXISTS")
        partial = sum(1 for a in group if a.get("build_state") == "PARTIAL")
        missing = sum(1 for a in group if a.get("build_state") == "MISSING")
        na = sum(1 for a in group if a.get("build_state") == "N/A")
        lines.append(
            f"| {pillar} | {total} | {exists} | {partial} | {missing} | {na} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")

    # Detail per pillar
    all_pillars = PILLAR_ORDER + other_pillars
    for pillar in all_pillars:
        group = pillar_atoms.get(pillar, [])
        if not group:
            continue

        # Nature distribution
        nature_counts = defaultdict(int)
        for a in group:
            nature_counts[a.get("nature", "UNKNOWN")] += 1

        lines.append(f"## {pillar}")
        lines.append(f"Total: {len(group)}")
        lines.append("")
        lines.append("### Nature Distribution")
        lines.append("")
        lines.append("| Nature | Count |")
        lines.append("|--------|-------|")
        for nature, count in sorted(
            nature_counts.items(), key=lambda x: -x[1]
        ):
            lines.append(f"| {nature} | {count} |")

        lines.append("")
        lines.append("### Atoms")
        lines.append("")
        lines.append(
            "| ID | Source | Idea | Nature | Build State |"
        )
        lines.append(
            "|-----|--------|------|--------|-------------|"
        )
        sorted_group = sorted(
            group,
            key=lambda a: (
                BUILD_PRIORITY.get(a.get("build_state", "N/A"), 99),
                a.get("id", ""),
            ),
        )
        for a in sorted_group:
            lines.append(
                f"| {a.get('id', '')} "
                f"| {esc(a.get('source_file', ''))} "
                f"| {truncate(a.get('idea', ''))} "
                f"| {a.get('nature', '')} "
                f"| {a.get('build_state', '')} |"
            )
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Coverage Map: By Provenance
# ---------------------------------------------------------------------------
def generate_by_provenance(atoms):
    prov_atoms = defaultdict(list)
    for atom in atoms:
        prov = atom.get("provenance", "UNKNOWN")
        prov_atoms[prov].append(atom)

    lines = [
        "# Coverage Map: By Provenance",
        "",
        f"Generated: {timestamp()}",
        f"Total atoms in registry: {len(atoms)}",
        "",
        "## Summary",
        "",
        "| Provenance | Total | EXISTS | PARTIAL | MISSING | N/A | Description |",
        "|------------|-------|--------|---------|---------|-----|-------------|",
    ]

    prov_desc = {
        "LOCAL": "Maddie's authentic voice — highest priority for preservation",
        "HYBRID": "Co-created content (Maddie + AI/external frameworks)",
        "ALIEN": "External references or third-party content",
    }

    for prov in PROVENANCE_ORDER:
        group = prov_atoms.get(prov, [])
        total = len(group)
        exists = sum(1 for a in group if a.get("build_state") == "EXISTS")
        partial = sum(1 for a in group if a.get("build_state") == "PARTIAL")
        missing = sum(1 for a in group if a.get("build_state") == "MISSING")
        na = sum(1 for a in group if a.get("build_state") == "N/A")
        desc = prov_desc.get(prov, "")
        lines.append(
            f"| **{prov}** | {total} | {exists} | {partial} | {missing} | {na} | {desc} |"
        )

    # Catch unknowns
    other_provs = sorted(set(prov_atoms.keys()) - set(PROVENANCE_ORDER))
    for prov in other_provs:
        group = prov_atoms[prov]
        total = len(group)
        exists = sum(1 for a in group if a.get("build_state") == "EXISTS")
        partial = sum(1 for a in group if a.get("build_state") == "PARTIAL")
        missing = sum(1 for a in group if a.get("build_state") == "MISSING")
        na = sum(1 for a in group if a.get("build_state") == "N/A")
        lines.append(
            f"| {prov} | {total} | {exists} | {partial} | {missing} | {na} | |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")

    # Detail per provenance
    all_provs = PROVENANCE_ORDER + other_provs
    for prov in all_provs:
        group = prov_atoms.get(prov, [])
        if not group:
            continue

        lines.append(f"## {prov}")
        lines.append(f"Total: {len(group)} | {prov_desc.get(prov, '')}")
        lines.append("")

        # Nature breakdown
        nature_counts = defaultdict(int)
        for a in group:
            nature_counts[a.get("nature", "UNKNOWN")] += 1

        lines.append("### Nature Distribution")
        lines.append("")
        lines.append("| Nature | Count |")
        lines.append("|--------|-------|")
        for nature, count in sorted(nature_counts.items(), key=lambda x: -x[1]):
            lines.append(f"| {nature} | {count} |")
        lines.append("")

        # Build state breakdown
        build_counts = defaultdict(int)
        for a in group:
            build_counts[a.get("build_state", "UNKNOWN")] += 1

        lines.append("### Build State Distribution")
        lines.append("")
        lines.append("| Build State | Count |")
        lines.append("|-------------|-------|")
        for bs, count in sorted(build_counts.items(), key=lambda x: -x[1]):
            lines.append(f"| {bs} | {count} |")
        lines.append("")

        # Atom listing
        lines.append("### Atoms")
        lines.append("")
        lines.append(
            "| ID | Source | Idea | Nature | Build State | Pillar |"
        )
        lines.append(
            "|-----|--------|------|--------|-------------|--------|"
        )
        sorted_group = sorted(
            group,
            key=lambda a: (
                BUILD_PRIORITY.get(a.get("build_state", "N/A"), 99),
                a.get("id", ""),
            ),
        )
        for a in sorted_group:
            lines.append(
                f"| {a.get('id', '')} "
                f"| {esc(a.get('source_file', ''))} "
                f"| {truncate(a.get('idea', ''))} "
                f"| {a.get('nature', '')} "
                f"| {a.get('build_state', '')} "
                f"| {a.get('pillar', '')} |"
            )
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Coverage Map: By Nature
# ---------------------------------------------------------------------------
def generate_by_nature(atoms):
    nature_atoms = defaultdict(list)
    for atom in atoms:
        nature = atom.get("nature", "UNKNOWN")
        nature_atoms[nature].append(atom)

    # Sort natures by count descending
    sorted_natures = sorted(nature_atoms.keys(), key=lambda n: -len(nature_atoms[n]))

    lines = [
        "# Coverage Map: By Nature",
        "",
        f"Generated: {timestamp()}",
        f"Total atoms in registry: {len(atoms)}",
        "",
        "## Summary",
        "",
        "| Nature | Total | EXISTS | PARTIAL | MISSING | N/A |",
        "|--------|-------|--------|---------|---------|-----|",
    ]

    for nature in sorted_natures:
        group = nature_atoms[nature]
        total = len(group)
        exists = sum(1 for a in group if a.get("build_state") == "EXISTS")
        partial = sum(1 for a in group if a.get("build_state") == "PARTIAL")
        missing = sum(1 for a in group if a.get("build_state") == "MISSING")
        na = sum(1 for a in group if a.get("build_state") == "N/A")
        lines.append(
            f"| {nature} | {total} | {exists} | {partial} | {missing} | {na} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")

    # Detail per nature with top 5 by build priority
    for nature in sorted_natures:
        group = nature_atoms[nature]
        total = len(group)

        lines.append(f"## {nature}")
        lines.append(f"Total: {total}")
        lines.append("")

        # Top 5 by build priority (MISSING first, then PARTIAL)
        priority_sorted = sorted(
            group,
            key=lambda a: (
                BUILD_PRIORITY.get(a.get("build_state", "N/A"), 99),
                a.get("id", ""),
            ),
        )
        top5 = priority_sorted[:5]

        lines.append("### Top 5 by Build Priority")
        lines.append("")
        lines.append(
            "| ID | Source | Idea | Provenance | Build State | Pillar |"
        )
        lines.append(
            "|-----|--------|------|------------|-------------|--------|"
        )
        for a in top5:
            lines.append(
                f"| {a.get('id', '')} "
                f"| {esc(a.get('source_file', ''))} "
                f"| {truncate(a.get('idea', ''))} "
                f"| {a.get('provenance', '')} "
                f"| {a.get('build_state', '')} "
                f"| {a.get('pillar', '')} |"
            )
        lines.append("")

        # Full listing
        lines.append(f"### All {nature} Atoms ({total})")
        lines.append("")
        lines.append(
            "| ID | Source | Idea | Provenance | Build State | Pillar |"
        )
        lines.append(
            "|-----|--------|------|------------|-------------|--------|"
        )
        for a in priority_sorted:
            lines.append(
                f"| {a.get('id', '')} "
                f"| {esc(a.get('source_file', ''))} "
                f"| {truncate(a.get('idea', ''))} "
                f"| {a.get('provenance', '')} "
                f"| {a.get('build_state', '')} "
                f"| {a.get('pillar', '')} |"
            )
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Strike Plans
# ---------------------------------------------------------------------------
def atom_row(a):
    return (
        f"| {a.get('id', '')} "
        f"| {esc(a.get('source_file', ''))} "
        f"| {truncate(a.get('idea', ''))} "
        f"| {a.get('provenance', '')} "
        f"| {a.get('nature', '')} "
        f"| {a.get('build_state', '')} |"
    )


def strike_table_header():
    return (
        "| ID | Source | Idea | Provenance | Nature | Build State |\n"
        "|-----|--------|------|------------|--------|-------------|"
    )


def sort_atoms(group):
    return sorted(
        group,
        key=lambda a: (
            BUILD_PRIORITY.get(a.get("build_state", "N/A"), 99),
            a.get("id", ""),
        ),
    )


def generate_phase_1(atoms):
    """Foundation (UNBLOCKED)"""
    # Strike 1A: Architecture atoms (nature: FRAMEWORK, MODEL, INSTRUCTION from root docs)
    strike_1a = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("1A")
        and a.get("nature") in ("FRAMEWORK", "MODEL", "INSTRUCTION")
    ]

    # Strike 1B: Editorial triage (editorial: FLAGGED)
    strike_1b = [a for a in atoms if a.get("editorial") == "FLAGGED"]

    # Strike 1C: Client decision extraction (nature: QUESTION, INSTRUCTION)
    strike_1c = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("1")
        and a.get("nature") in ("QUESTION", "INSTRUCTION")
    ]

    lines = [
        "# Strike Plan: Phase 1 — Foundation (UNBLOCKED)",
        "",
        f"Generated: {timestamp()}",
        "",
        "Phase 1 establishes the architectural and editorial foundation.",
        "No external blockers — all work can begin immediately.",
        "",
        "---",
        "",
        f"## Strike 1A: Architecture Atoms ({len(strike_1a)})",
        "",
        "Atoms with nature FRAMEWORK, MODEL, or INSTRUCTION from foundational source documents.",
        "These define the structural skeleton of the spiral system.",
        "",
        strike_table_header(),
    ]
    for a in sort_atoms(strike_1a):
        lines.append(atom_row(a))

    lines.extend([
        "",
        "---",
        "",
        f"## Strike 1B: Editorial Triage ({len(strike_1b)})",
        "",
        "All atoms flagged for editorial review. These require human decision",
        "before they can advance to any build state.",
        "",
        strike_table_header(),
    ])
    for a in sort_atoms(strike_1b):
        lines.append(atom_row(a))

    lines.extend([
        "",
        "---",
        "",
        f"## Strike 1C: Client Decision Extraction ({len(strike_1c)})",
        "",
        "QUESTION and INSTRUCTION atoms from Phase 1 — decisions Maddie needs to make",
        "or directives that need to be confirmed before build proceeds.",
        "",
        strike_table_header(),
    ])
    for a in sort_atoms(strike_1c):
        lines.append(atom_row(a))

    total = len(set(a["id"] for a in strike_1a + strike_1b + strike_1c))
    lines.extend([
        "",
        "---",
        "",
        f"## Phase 1 Summary",
        "",
        f"| Strike | Count |",
        f"|--------|-------|",
        f"| 1A — Architecture | {len(strike_1a)} |",
        f"| 1B — Editorial Triage | {len(strike_1b)} |",
        f"| 1C — Client Decisions | {len(strike_1c)} |",
        f"| **Unique atoms** | **{total}** |",
    ])

    return "\n".join(lines)


def generate_phase_2(atoms):
    """Physical Sovereignty (blocked by GH#13, GH#17)"""
    # Strike 2A: Node 1-5 deep-dive content
    strike_2a = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("2A")
        or (
            a.get("strike_phase", "").startswith("2")
            and any(n in a.get("nodes", []) for n in [1, 2, 3, 4, 5])
            and a.get("nature") not in ("TOOL",)
        )
    ]

    # Strike 2B: Water funnel atoms
    strike_2b = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("2B")
        or (
            a.get("strike_phase", "").startswith("2")
            and a.get("pillar") == "Physical"
            and "water" in a.get("idea", "").lower()
        )
    ]

    # Strike 2C: Branch enrichment (build_state: PARTIAL for existing branches)
    strike_2c = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("2C")
        or (
            a.get("strike_phase", "").startswith("2")
            and a.get("build_state") == "PARTIAL"
            and a.get("pillar") == "Physical"
        )
    ]

    # Strike 2D: Standalone health tools (nature: TOOL)
    strike_2d = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("2D")
        or (
            a.get("strike_phase", "").startswith("2")
            and a.get("nature") == "TOOL"
        )
    ]

    lines = [
        "# Strike Plan: Phase 2 — Physical Sovereignty",
        "",
        f"Generated: {timestamp()}",
        "",
        "**Blocked by:** GH#13 (final node architecture), GH#17 (water funnel spec)",
        "",
        "Phase 2 builds the Physical Sovereignty pillar — nodes 1-5,",
        "the water funnel, branch enrichment, and standalone health tools.",
        "",
        "---",
        "",
        f"## Strike 2A: Node 1-5 Deep-Dive Content ({len(strike_2a)})",
        "",
        "Content atoms mapped to the first five spiral nodes (Physical domain).",
        "",
        strike_table_header(),
    ]
    for a in sort_atoms(strike_2a):
        lines.append(atom_row(a))

    lines.extend([
        "",
        "---",
        "",
        f"## Strike 2B: Water Funnel Atoms ({len(strike_2b)})",
        "",
        "Atoms specifically related to the Stop Drinking Acid / water funnel.",
        "",
        strike_table_header(),
    ])
    for a in sort_atoms(strike_2b):
        lines.append(atom_row(a))

    lines.extend([
        "",
        "---",
        "",
        f"## Strike 2C: Branch Enrichment ({len(strike_2c)})",
        "",
        "PARTIAL-state Physical atoms — existing branch content that needs deepening.",
        "",
        strike_table_header(),
    ])
    for a in sort_atoms(strike_2c):
        lines.append(atom_row(a))

    lines.extend([
        "",
        "---",
        "",
        f"## Strike 2D: Standalone Health Tools ({len(strike_2d)})",
        "",
        "TOOL-nature atoms in the Physical Sovereignty scope.",
        "",
        strike_table_header(),
    ])
    for a in sort_atoms(strike_2d):
        lines.append(atom_row(a))

    unique_ids = set()
    for group in [strike_2a, strike_2b, strike_2c, strike_2d]:
        for a in group:
            unique_ids.add(a.get("id"))
    total = len(unique_ids)

    lines.extend([
        "",
        "---",
        "",
        "## Phase 2 Summary",
        "",
        "| Strike | Count |",
        "|--------|-------|",
        f"| 2A — Node 1-5 Content | {len(strike_2a)} |",
        f"| 2B — Water Funnel | {len(strike_2b)} |",
        f"| 2C — Branch Enrichment | {len(strike_2c)} |",
        f"| 2D — Health Tools | {len(strike_2d)} |",
        f"| **Unique atoms** | **{total}** |",
    ])

    return "\n".join(lines)


def generate_phase_3(atoms):
    """Inner + Identity (blocked by Phase 2)"""
    # Strike 3A: Node 6-9 Inner Sovereignty
    strike_3a = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("3A")
        or (
            a.get("strike_phase", "").startswith("3")
            and any(n in a.get("nodes", []) for n in [6, 7, 8, 9])
            and a.get("nature") not in ("TOOL",)
        )
    ]

    # Strike 3B: Node 10-12 Identity Sovereignty
    strike_3b = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("3B")
        or (
            a.get("strike_phase", "").startswith("3")
            and any(n in a.get("nodes", []) for n in [10, 11, 12])
            and a.get("nature") not in ("TOOL",)
        )
    ]

    # Strike 3C: Standalone mindset tools
    strike_3c = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("3C")
        or (
            a.get("strike_phase", "").startswith("3")
            and a.get("nature") == "TOOL"
        )
    ]

    lines = [
        "# Strike Plan: Phase 3 — Inner + Identity Sovereignty",
        "",
        f"Generated: {timestamp()}",
        "",
        "**Blocked by:** Phase 2 completion",
        "",
        "Phase 3 builds the Inner Sovereignty (nodes 6-9) and Identity Sovereignty",
        "(nodes 10-12) pillars, plus standalone mindset tools.",
        "",
        "---",
        "",
        f"## Strike 3A: Node 6-9 Inner Sovereignty ({len(strike_3a)})",
        "",
        "Content atoms for Awareness, Thought Patterns, Pattern Recognition,",
        "and Reality Interpretation.",
        "",
        strike_table_header(),
    ]
    for a in sort_atoms(strike_3a):
        lines.append(atom_row(a))

    lines.extend([
        "",
        "---",
        "",
        f"## Strike 3B: Node 10-12 Identity Sovereignty ({len(strike_3b)})",
        "",
        "Content atoms for Radical Responsibility, Acknowledgment, and Integrity.",
        "",
        strike_table_header(),
    ])
    for a in sort_atoms(strike_3b):
        lines.append(atom_row(a))

    lines.extend([
        "",
        "---",
        "",
        f"## Strike 3C: Standalone Mindset Tools ({len(strike_3c)})",
        "",
        "TOOL-nature atoms in the Inner + Identity scope.",
        "",
        strike_table_header(),
    ])
    for a in sort_atoms(strike_3c):
        lines.append(atom_row(a))

    unique_ids = set()
    for group in [strike_3a, strike_3b, strike_3c]:
        for a in group:
            unique_ids.add(a.get("id"))
    total = len(unique_ids)

    lines.extend([
        "",
        "---",
        "",
        "## Phase 3 Summary",
        "",
        "| Strike | Count |",
        "|--------|-------|",
        f"| 3A — Inner Sovereignty (6-9) | {len(strike_3a)} |",
        f"| 3B — Identity Sovereignty (10-12) | {len(strike_3b)} |",
        f"| 3C — Mindset Tools | {len(strike_3c)} |",
        f"| **Unique atoms** | **{total}** |",
    ])

    return "\n".join(lines)


def generate_phase_4(atoms):
    """Financial + Expansion"""
    # Strike 4A: Node 13 Financial Sovereignty
    strike_4a = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("4A")
        or (
            a.get("strike_phase", "").startswith("4")
            and 13 in (a.get("nodes", []) if isinstance(a.get("nodes", []), list) else [a.get("nodes")])
        )
    ]

    # Strike 4B: Standalone products (nature: PRODUCT)
    strike_4b = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("4B")
        or (
            a.get("strike_phase", "").startswith("4")
            and a.get("nature") == "PRODUCT"
        )
    ]

    # Strike 4C: Social content pipeline (nature: SCRIPT)
    strike_4c = [
        a
        for a in atoms
        if a.get("strike_phase", "").startswith("4C")
        or (
            a.get("strike_phase", "").startswith("4")
            and a.get("nature") == "SCRIPT"
        )
    ]

    lines = [
        "# Strike Plan: Phase 4 — Financial Sovereignty + Expansion",
        "",
        f"Generated: {timestamp()}",
        "",
        "Phase 4 builds the Financial Sovereignty pillar (node 13),",
        "standalone products, and the social content pipeline.",
        "",
        "---",
        "",
        f"## Strike 4A: Node 13 Financial Sovereignty ({len(strike_4a)})",
        "",
        "Content atoms for Systems Create Freedom — business, sales,",
        "brand building, wealth energetics.",
        "",
        strike_table_header(),
    ]
    for a in sort_atoms(strike_4a):
        lines.append(atom_row(a))

    lines.extend([
        "",
        "---",
        "",
        f"## Strike 4B: Standalone Products ({len(strike_4b)})",
        "",
        "PRODUCT-nature atoms — digital products, courses, subscriptions.",
        "",
        strike_table_header(),
    ])
    for a in sort_atoms(strike_4b):
        lines.append(atom_row(a))

    lines.extend([
        "",
        "---",
        "",
        f"## Strike 4C: Social Content Pipeline ({len(strike_4c)})",
        "",
        "SCRIPT-nature atoms — reel scripts, content repurposing, social automation.",
        "",
        strike_table_header(),
    ])
    for a in sort_atoms(strike_4c):
        lines.append(atom_row(a))

    unique_ids = set()
    for group in [strike_4a, strike_4b, strike_4c]:
        for a in group:
            unique_ids.add(a.get("id"))
    total = len(unique_ids)

    lines.extend([
        "",
        "---",
        "",
        "## Phase 4 Summary",
        "",
        "| Strike | Count |",
        "|--------|-------|",
        f"| 4A — Financial Sovereignty (Node 13) | {len(strike_4a)} |",
        f"| 4B — Standalone Products | {len(strike_4b)} |",
        f"| 4C — Social Content Pipeline | {len(strike_4c)} |",
        f"| **Unique atoms** | **{total}** |",
    ])

    return "\n".join(lines)


def generate_phase_5(atoms):
    """Proof & Close"""
    total = len(atoms)
    exists = sum(1 for a in atoms if a.get("build_state") == "EXISTS")
    partial = sum(1 for a in atoms if a.get("build_state") == "PARTIAL")
    missing = sum(1 for a in atoms if a.get("build_state") == "MISSING")
    na = sum(1 for a in atoms if a.get("build_state") == "N/A")

    # Coverage by phase
    phase_counts = defaultdict(lambda: {"total": 0, "EXISTS": 0, "PARTIAL": 0, "MISSING": 0, "N/A": 0})
    for a in atoms:
        sp = a.get("strike_phase", "unassigned")
        phase_prefix = sp[0] if sp and sp[0].isdigit() else "unassigned"
        phase_counts[phase_prefix]["total"] += 1
        bs = a.get("build_state", "N/A")
        if bs in phase_counts[phase_prefix]:
            phase_counts[phase_prefix][bs] += 1

    # Provenance coverage
    prov_counts = defaultdict(lambda: {"total": 0, "EXISTS": 0, "MISSING": 0})
    for a in atoms:
        prov = a.get("provenance", "UNKNOWN")
        prov_counts[prov]["total"] += 1
        bs = a.get("build_state", "N/A")
        if bs == "EXISTS":
            prov_counts[prov]["EXISTS"] += 1
        elif bs == "MISSING":
            prov_counts[prov]["MISSING"] += 1

    lines = [
        "# Strike Plan: Phase 5 — Proof & Close",
        "",
        f"Generated: {timestamp()}",
        "",
        "Phase 5 is the verification pass. No new content is created —",
        "this phase confirms that all atoms have been accounted for",
        "and the build is complete.",
        "",
        "---",
        "",
        "## Coverage Verification Summary",
        "",
        "### Overall",
        "",
        "| Metric | Count | Pct |",
        "|--------|-------|-----|",
        f"| Total atoms | {total} | 100% |",
        f"| EXISTS | {exists} | {exists*100//total}% |",
        f"| PARTIAL | {partial} | {partial*100//total}% |",
        f"| MISSING | {missing} | {missing*100//total}% |",
        f"| N/A | {na} | {na*100//total}% |",
        "",
        "### By Phase",
        "",
        "| Phase | Total | EXISTS | PARTIAL | MISSING | N/A |",
        "|-------|-------|--------|---------|---------|-----|",
    ]

    for phase in ["1", "2", "3", "4"]:
        pc = phase_counts.get(phase, {"total": 0, "EXISTS": 0, "PARTIAL": 0, "MISSING": 0, "N/A": 0})
        lines.append(
            f"| Phase {phase} | {pc['total']} | {pc['EXISTS']} | {pc['PARTIAL']} | {pc['MISSING']} | {pc['N/A']} |"
        )
    pc_u = phase_counts.get("unassigned", {"total": 0, "EXISTS": 0, "PARTIAL": 0, "MISSING": 0, "N/A": 0})
    if pc_u["total"] > 0:
        lines.append(
            f"| Unassigned | {pc_u['total']} | {pc_u['EXISTS']} | {pc_u['PARTIAL']} | {pc_u['MISSING']} | {pc_u['N/A']} |"
        )

    lines.extend([
        "",
        "### By Provenance",
        "",
        "| Provenance | Total | EXISTS | MISSING | Coverage |",
        "|------------|-------|--------|---------|----------|",
    ])
    for prov in PROVENANCE_ORDER:
        pc = prov_counts.get(prov, {"total": 0, "EXISTS": 0, "MISSING": 0})
        t = pc["total"]
        e = pc["EXISTS"]
        m = pc["MISSING"]
        pct = f"{e*100//t}%" if t > 0 else "0%"
        lines.append(f"| {prov} | {t} | {e} | {m} | {pct} |")

    lines.extend([
        "",
        "### By Node Coverage",
        "",
        "| Node | Name | Total | EXISTS | MISSING |",
        "|------|------|-------|--------|---------|",
    ])

    node_counts = defaultdict(lambda: {"total": 0, "EXISTS": 0, "MISSING": 0})
    for a in atoms:
        nodes = a.get("nodes", [])
        if isinstance(nodes, list):
            for n in nodes:
                node_counts[n]["total"] += 1
                bs = a.get("build_state", "N/A")
                if bs == "EXISTS":
                    node_counts[n]["EXISTS"] += 1
                elif bs == "MISSING":
                    node_counts[n]["MISSING"] += 1
        elif isinstance(nodes, int):
            node_counts[nodes]["total"] += 1
            bs = a.get("build_state", "N/A")
            if bs == "EXISTS":
                node_counts[nodes]["EXISTS"] += 1
            elif bs == "MISSING":
                node_counts[nodes]["MISSING"] += 1

    for nid in sorted(NODE_NAMES.keys()):
        nc = node_counts.get(nid, {"total": 0, "EXISTS": 0, "MISSING": 0})
        lines.append(
            f"| {nid} | {NODE_NAMES[nid]} | {nc['total']} | {nc['EXISTS']} | {nc['MISSING']} |"
        )

    lines.extend([
        "",
        "---",
        "",
        "## Verification Checklist",
        "",
        "- [ ] All MISSING atoms reviewed — confirm intentional omission or create build tickets",
        "- [ ] All FLAGGED atoms resolved (editorial decisions made)",
        "- [ ] LOCAL provenance atoms preserved with Maddie's authentic voice",
        "- [ ] Node coverage balanced across all 13 spiral nodes",
        "- [ ] Pillar coverage balanced across all 4 pillars",
        "- [ ] Cross-cutting atoms integrated into hub architecture",
        "- [ ] proof.md regenerated and showing PROOF COMPLETE",
        "",
        "## Proof Link",
        "",
        "See [proof.md](../coverage/proof.md) for the canonical proof status.",
        "",
        f"Current status: **{total} atoms registered, {exists + partial} in build ({(exists+partial)*100//total}%).**",
    ])

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print("Loading atom registry...")
    atoms = load_registry()
    print(f"  Loaded {len(atoms)} atoms")

    os.makedirs(COVERAGE_DIR, exist_ok=True)
    os.makedirs(STRIKES_DIR, exist_ok=True)

    # Coverage maps
    files = {
        os.path.join(COVERAGE_DIR, "by-node.md"): generate_by_node,
        os.path.join(COVERAGE_DIR, "by-pillar.md"): generate_by_pillar,
        os.path.join(COVERAGE_DIR, "by-provenance.md"): generate_by_provenance,
        os.path.join(COVERAGE_DIR, "by-nature.md"): generate_by_nature,
    }

    for path, generator in files.items():
        print(f"  Generating {os.path.basename(path)}...")
        content = generator(atoms)
        with open(path, "w") as f:
            f.write(content)
            f.write("\n")

    # Strike plans
    strike_files = {
        os.path.join(STRIKES_DIR, "phase-1.md"): generate_phase_1,
        os.path.join(STRIKES_DIR, "phase-2.md"): generate_phase_2,
        os.path.join(STRIKES_DIR, "phase-3.md"): generate_phase_3,
        os.path.join(STRIKES_DIR, "phase-4.md"): generate_phase_4,
        os.path.join(STRIKES_DIR, "phase-5.md"): generate_phase_5,
    }

    for path, generator in strike_files.items():
        print(f"  Generating {os.path.basename(path)}...")
        content = generator(atoms)
        with open(path, "w") as f:
            f.write(content)
            f.write("\n")

    print(f"\nDone. Generated 4 coverage maps + 5 strike plans from {len(atoms)} atoms.")


if __name__ == "__main__":
    main()
